version: "3.9"

services:
  frontend:
    build: ./AssetTracker
    ports:
      - "5173:5173"
    env_file:
      - ./AssetTracker/.env
    depends_on:
      - backend
    volumes:
      - ./AssetTracker:/app
      - /app/node_modules
    command: ["npm", "run", "dev", "--", "--host"]

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    depends_on:
      - db
      - redis
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: ["sh", "-c", "npx wait-on tcp:db:5432 && npm run dev"]

  db:
    image: postgres:16
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: shariful
      POSTGRES_DB: Demo
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432" # optional for host access

  redis:
    image: redis:7
    container_name: redis

volumes:
  postgres_data:
